# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='youtubevid',
            field=models.CharField(editable=False, max_length=16, null=True),
        ),
    ]
