# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171024_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='main.Subjects'),
        ),
    ]
