# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171024_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='subject',
            new_name='chapter',
        ),
        migrations.AddField(
            model_name='videos',
            name='slug',
            field=models.SlugField(editable=False, max_length=300, null=True),
        ),
    ]
